### ISSUE TITLE
osm-search and osm-install invalid osm.appstores references

### ISSUE THREAD

**Issue by NeonDaniel** [OpenVoiceOS/ovos_skill_manager#15]
OSM scripts reference `osm.appstores` as a dict indexed by name, but that property returns a list.

```
Traceback (most recent call last):
  File "/usr/bin/osm-search", line 11, in <module>
    load_entry_point('ovos-skills-manager==0.0.3', 'console_scripts', 'osm-search')()
  File "/usr/lib/python3.8/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3.8/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3.8/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3.8/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/usr/lib/python3.8/site-packages/ovos_skills_manager/scripts/search.py", line 68, in search
    skills = search_skill(method, query, fuzzy, no_ignore_case,
  File "/usr/lib/python3.8/site-packages/ovos_skills_manager/scripts/search.py", line 12, in search_skill
    set_github_token(osm.appstores[appstore].get("auth_token"))
TypeError: list indices must be integers or slices, not str
```

**Comment by JarbasAl** [comment]
this is fixed by #14
